//
//  GIFObjectsShowPresenter.swift
//  GiphyAppDemo
//
//  Created by msm72 on 02.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol GIFObjectsShowPresentationLogic {
    func presentSomething(response: GIFObjectsShowModels.FetchGIFObjects.ResponseModel)
}

class GIFObjectsShowPresenter: GIFObjectsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: GIFObjectsShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: GIFObjectsShowModels.FetchGIFObjects.ResponseModel) {
        let viewModel = GIFObjectsShowModels.FetchGIFObjects.ViewModel()
        viewController?.displayFetchGIFObjects(fromViewModel: viewModel)
    }
}
