//
//  GIFObjectsShowInteractor.swift
//  GiphyAppDemo
//
//  Created by msm72 on 02.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol GIFObjectsShowBusinessLogic {
    func fetchGIFObjects(withRequestModel requestModel: GIFObjectsShowModels.FetchGIFObjects.RequestModel)
}

protocol GIFObjectsShowDataStore {
    var objectsGIF: [String]? { get }
}

class GIFObjectsShowInteractor: GIFObjectsShowBusinessLogic, GIFObjectsShowDataStore {
    // MARK: - Properties
    var presenter: GIFObjectsShowPresentationLogic?
    var worker: GIFObjectsShowWorker?

    var objectsGIF: [String]?
    
    
    // MARK: - Business logic implementation
    func fetchGIFObjects(withRequestModel requestModel: GIFObjectsShowModels.FetchGIFObjects.RequestModel) {
        worker = GIFObjectsShowWorker()
        
        let url = worker?.createURL(withParameterQ: requestModel.parameterQ, andParameterOffset: requestModel.parameterOffset)
        print(url!)
        
        worker?.fetchGIFObjects(witURL: url!, completionHandler: { (objectsGIF) in
            let responseModel = GIFObjectsShowModels.FetchGIFObjects.ResponseModel()
            self.presenter?.presentSomething(response: responseModel)
        })
    }
}
