//
//  GIFObjectShowPresenter.swift
//  GiphyAppDemo
//
//  Created by msm72 on 02.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol GIFObjectShowPresentationLogic {
    func presentSomething(response: GIFObjectShowModels.Something.ResponseModel)
}

class GIFObjectShowPresenter: GIFObjectShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: GIFObjectShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: GIFObjectShowModels.Something.ResponseModel) {
        let viewModel = GIFObjectShowModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
