//
//  GIFObjectShowInteractor.swift
//  GiphyAppDemo
//
//  Created by msm72 on 02.11.2017.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol GIFObjectShowBusinessLogic {
    func doSomething(request: GIFObjectShowModels.Something.RequestModel)
}

protocol GIFObjectShowDataStore {
    var objectGIF: ObjectGIF! { get set }
}

class GIFObjectShowInteractor: GIFObjectShowBusinessLogic, GIFObjectShowDataStore {
    // MARK: - Properties
    var presenter: GIFObjectShowPresentationLogic?
    var worker: GIFObjectShowWorker?
    
    var objectGIF: ObjectGIF!

    
    // MARK: - Business logic implementation
    func doSomething(request: GIFObjectShowModels.Something.RequestModel) {
        worker = GIFObjectShowWorker()
        worker?.doSomeWork()
        
        let responseModel = GIFObjectShowModels.Something.ResponseModel()
        presenter?.presentSomething(response: responseModel)
    }
}
